name = "NMRAnalysis"
uuid = "e8f11e50-668f-4bdf-b40b-95f76662da30"
version = "0.2.6"
authors = ["Chris Waudby", "Sophia Hazlett"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
NMRTools = "c2839fe3-f1de-42fc-897f-c1b0e8db4db6"
NativeFileDialog = "e1fe445b-aa65-4df4-81c1-2041507f0fd4"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CairoMakie = "0.15.7"
DelimitedFiles = "1.9.1"
Distributions = "0.25.117"
GLMakie = "0.13.7"
LightGraphs = "1.3.5"
LinearAlgebra = "1.10.0"
LsqFit = "0.15"
Measurements = "2.11"
MonteCarloMeasurements = "1.4.5"
NMRTools = "0.2.3"
NativeFileDialog = "0.2.1"
OrderedCollections = "1.8"
Plots = "1.40"
PrecompileTools = "1.2"
Printf = "1.10.0"
REPL = "1.10"
Random = "1.10"
Reexport = "1.2"
SafeTestsets = "0.1"
Statistics = "1.10"
julia = "1.10"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
