name = "NMRAnalysis"
uuid = "e8f11e50-668f-4bdf-b40b-95f76662da30"
authors = ["Chris Waudby"]
version = "0.2.1"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
NMRTools = "c2839fe3-f1de-42fc-897f-c1b0e8db4db6"
NativeFileDialog = "e1fe445b-aa65-4df4-81c1-2041507f0fd4"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CairoMakie = "0.13.1"
DelimitedFiles = "1.9.1"
GLMakie = "0.11"
LightGraphs = "1.3.5"
LsqFit = "0.15.0"
Measurements = "2.11"
NMRTools = "0.1.11"
NativeFileDialog = "0.2.1"
OrderedCollections = "1.7.0"
Plots = "1.40"
PrecompileTools = "1.2"
Reexport = "1.2"
SafeTestsets = "0.1"
Statistics = "1.10"
julia = "1.10"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
